lockserv:
  image: lockserv
  environment:
    # The start of active environment variables. Set as needed.
    - MONGODB_IP=database
    # - MONGODB_PORT=27890
    # - MONGODB_DATABASE=USEHASKELLDB
    - LOG_LEVEL=DEBUG
    # - https_proxy=http://www-proxy.scss.tcd.ie:8080
    # - http_proxy=http://www-proxy.scss.tcd.ie:8080
  command:  /usr/local/bin/lockService-exe
  ports:
    - "8080:8080"
  links:
    - database
 
 
database:
  image: mongo:3.0.2
  ports:
    - "27890:27017"
