lockserv:
  image: lockserv
  environment:
    # The start of active environment variables. Set as needed.
    - MONGODB_IP=database22
    # - MONGODB_PORT
    # - MONGODB_DATABASE=USE_HASKELL_DB
    - LOG_LEVEL=DEBUG
    # - https_proxy=http://www-proxy.scss.tcd.ie:8080
    # - http_proxy=http://www-proxy.scss.tcd.ie:8080
  command:  /usr/local/bin/lockService-exe
  ports:
    - "8077:8081"
  links:
    - database22
database22:
  image: mongo:3.0.2
  ports:
    - "27010:27017"