version: '2'
services:
  db:
    image: mongo
    environment:
      DNSDOCK_NAME: cache
      DNSDOCK_IMAGE: authserver
    ports:
      - "27017:27017"
    network_mode: "mybridge"
  authserver:
    build: . 
    image: authserver
    environment:
      MONGO_HOST: cache.authserver.docker 
      HOST: api.authserver.docker
      DNSDOCK_NAME: api
      DNSDOCK_IMAGE: authserver
    ports:
      - "8080:8080"
    network_mode: "mybridge"
    #container_name: auth_master
    #network_mode: "host" 
    command: python auth_server.py 
    
